services:
  socboard-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: "socboard-frontend"
    # container_name: ${FRONTEND_HOST}
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
    command: npm run dev
    networks:
      - net

  # socboard-backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   container_name: "socboard-backend"
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #     - "5678:5678"
  #   # для общих миграций
  #   volumes:
  #     - ./backend:/app
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./backend
  #         target: /app
  #   depends_on:
  #     socboard-db:
  #       condition: service_healthy
  #     socboard-redis:
  #       condition: service_healthy
  #   networks:
  #     - net

  socboard-nginx:
    image: nginx:1.27-alpine
    container_name: "socboard-nginx"
    hostname: nginx
    depends_on:
      - socboard-frontend
      # - socboard-backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net

volumes:
  socboard_db:

networks:
  net:
    external: true
