services:
  socboard-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: "socboard-frontend"
    # container_name: ${FRONTEND_HOST}
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
    command: npm run dev
    networks:
      - net

  socboard-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: "socboard-backend"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    networks:
      - net

  socboard-nginx:
    image: nginx:1.27-alpine
    container_name: "socboard-nginx"
    hostname: nginx
    depends_on:
      - socboard-frontend
      - socboard-backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net

volumes:
  socboard_db:

networks:
  net:
    external: true
